%\VignetteIndexEntry{example on adaptive sampling}
%\VignetteKeywords{tgp}
%\VignetteDepends{tgp,akima,maptree,combinat}
%\VignettePackage{tgp}

\subsection{Adaptive Sampling}
\label{sec:as}

<<echo=false,results=hide>>=
library(tgp)
library(akima)
library(maptree)
options(width=70)
@ 

In this section, sequential design of experiments, a.k.a. {\em adaptive
sampling}, is demonstrated on the exponential data of Section
\ref{sec:exp}.  Gathering, again, the data:
<<>>=
exp2d.data <- exp2d.rand()
X <- exp2d.data$X; Z <- exp2d.data$Z
Xcand <- exp2d.data$XX
@ 
Start by fitting a treed GP LLM model to the data, without prediction,
in order to infer the MAP tree $\hat{\mathcal{T}}$.
<<echo=TRUE,results=HIDE>>=
exp1 <- btgpllm(X=X, Z=Z, pred.n=FALSE, corr="exp", R=2)
@ 
\begin{figure}[ht!]
\centering
<<label=mapt,fig=TRUE,echo=TRUE,width=6,height=5>>=
tgp.trees(exp1)
@
\vspace{-1cm}
\caption{\footnotesize MAP trees of each height encountered in the
  Markov chain for the exponential data.  $\hat{\mathcal{T}}$ is the
  one with the maximum $\log(p)$ above.}
\label{f:mapt}
\end{figure} 
The trees are shown in Figure \ref{f:mapt}.
Then, use the {\tt tgp.design} function to create $D$-optimal candidate
designs in each region of $\hat{\mathcal{T}}$.
<<>>=
XX <- tgp.design(10, Xcand, exp1)
@ 
Figure \ref{f:cands} shows the sampled {\tt XX} locations (circles)
amongst the input locations {\tt X} (dots) and MAP partition
$(\hat{\mathcal{T}})$.  Notice how the candidates {\tt XX} are spaced
out relative to themselves, and relative to the inputs {\tt X}, unless
they are near partition boundaries.  The placing of configurations
near region boundaries is a symptom particular to $D$-optimal designs.
This is desirable for experiments with {\tt tgp} models, as model
uncertainty is usually high there \cite{chaloner:1995}.
\begin{figure}[ht!]
\centering
<<label=cands,fig=TRUE,echo=TRUE,width=6,height=5>>=
plot(exp1$X, pch=19, cex=0.5); points(XX)
tgp.plot.parts.2d(exp1$parts)
@
\vspace{-0.5cm}
\caption{\footnotesize Treed $D$-optimal candidate locations {\tt XX}
  (circles), input locations {\tt X} (dots), and MAP tree
  $\hat{\mathcal{T}}$}
\label{f:cands}
\end{figure} 

Figure \ref{f:cands} uses the {\tt tgp.plot.parts.2d} function.
Unfortunately, this function is not well documented in the current
version of the {\tt tgp} package.  This should change in future
versions.

Now, the idea is to fit the treed GP LLM model, again, in order to
assess uncertainty in the predictive surface at those new candidate
design points.
<<echo=TRUE,results=HIDE>>=
exp1.btgpllm <- btgpllm(X=X, Z=Z, XX=XX, corr="exp", R=2)
@ 
Figure \ref{f:as} shows the posterior predictive surface.
The error surface, on the {\em right}, summarizes posterior predictive
uncertainty by a norm of quantiles.
\begin{figure}[ht!]
\centering
<<label=expas,fig=TRUE,echo=TRUE,width=12.5,height=7.5>>=
plot(exp1.btgpllm, main="ALM for treed GP LLM,")
@
\vspace{-0.5cm}
\caption{\footnotesize Treed $D$-optimal candidate locations {\tt XX}
  (circles), input locations {\tt X} (dots), and MAP tree
  $\hat{\mathcal{T}}$}
\label{f:as}
\end{figure} 
In accordance with the ALM algorithm, candidate locations {\tt XX}
with largest predictive error would be sampled (added into the design)
next.  These are most likely to be in the interesting region, i.e.,
the first quadrant. however, due to the random nature of this {\tt
  Sweave} document, this is not always the case.  Results depend
heavily on the clumping of the original design in the un-interesting
areas, and on the estimate of $\hat{\mathcal{T}}$.

Adaptive sampling via the ALC, or ego (or both) algorithms could
proceed by setting any/all of the {\tt Ds2x} or {\tt ego} parameters
to the {\tt b*} and {\tt tgp} to {\tt TRUE}.
