%\VignetteIndexEntry{example on motorcycle data}
%\VignetteKeywords{tgp}
%\VignetteDepends{tgp,akima,maptree,combinat}
%\VignettePackage{tgp}

\subsection{Motorcycle Accident Data}
\label{sec:moto}

<<echo=false,results=hide>>=
library(tgp)
library(akima)
library(maptree)
options(width=70)
@ 

The Motorcycle Accident Dataset \cite{silv:1985} is a classic
nonstationary data set used in recent literature
\cite{rasm:ghah:nips:2002} to demonstrate the success of nonstationary
models.  The data consists of measurements of acceleration of the
head of a motorcycle rider as a function of time in the first moments
after an impact.
In addition to being nonstationary, the data has input-dependent
noise, which makes it useful for illustrating how the treed GP model
handles this nuance.  There are at least two, and perhaps three
regions where the response exhibits different behavior both in terms
of the correlation structure and noise level.

The data is included as part of the {\tt MASS} library in {\tt R}.
<<>>= 
library(MASS)
@ 
Figure \ref{f:moto:bgp} shows how a stationary GP is able to capture
the nonlinearity in the response but fails to capture the input
dependent noise, and increased smoothness (perhaps linearity) in
parts of the input space.
<<echo=TRUE,results=HIDE>>=
moto.bgp <- bgp(X=mcycle[,1], Z=mcycle[,2], m0r1=TRUE)
@ 
Since the responses in this data have a wide range, it helps to
translate and rescale them so that they have a mean of zero, and a
range of one.  The {\tt m0r1} argument to {\tt b*} and {\tt tgp}
functions automates this procedure.  All progress indicators
are surpressed for this example.
\begin{figure}[ht!]
\centering
<<label=bgp,fig=TRUE,echo=TRUE,width=7,height=5>>=
plot(moto.bgp, main='GP,')
@
\vspace{-0.5cm}
\caption{\footnotesize Posterior predictive distribution using {\tt
    bgp} on the motorcycle accident data: mean and 90\% credible
  interval}
\label{f:moto:bgp}
\end{figure}

A Bayesian Linear CART model is able to capture the input dependent
noise but fails to capture the waviness of the
``whiplash''---center--- segment of th the response.
<<echo=TRUE,results=HIDE>>=
moto.btlm <- btlm(X=mcycle[,1], Z=mcycle[,2], m0r1=TRUE)
@ Figure \ref{f:moto:btlm} shows the resulting piecewise linear
predictive surface and MAP partition ($\hat{\mathcal{T}}$).
\begin{figure}[ht!]
\centering
<<label=btlm,fig=TRUE,echo=TRUE,width=7,height=5>>=
plot(moto.btlm, main='Bayesian CART,')
@
\vspace{-0.5cm}
\caption{\footnotesize Posterior predictive distribution using {\tt
    btlm} on the motorcycle accident data: mean and 90\% credible
  interval}
\label{f:moto:btlm}
\end{figure}

A treed GP model seems appropriate because it can model input
dependent smoothness {\em and} noise.  A treed GP LLM is probably
most appropriate since the left-hand part of the input space is likely
linear.  One might further hypothesize that the right-hand region is
also linear, perhaps with the same mean as the left-hand region, only
with higher noise.  The {\tt b*} and {\tt tgp} functions can force
an i.i.d.~hierarchical linear model by setting {\tt bprior=b0}.
Moreover, instead of rescaling the responses with {\tt m0r1}, one might
try encoding a mixture prior for the nugget in order to explicitly
model region-specific noise.  This requires direct usage of {\tt tgp}.
<<echo=TRUE,results=HIDE>>=
p <- tgp.default.params(2)
p$bprior <- "b0"
p$nug.p <- c(1.0,0.1,10.0,0.1)
moto.tgp <- tgp(X=mcycle[,1], Z=mcycle[,2], params=p,
	   BTE=c(2000,22000,2))
@ 
\begin{figure}[ht!]
\centering
<<label=btgp,fig=TRUE,echo=TRUE,width=7,height=5>>=
plot(moto.tgp, main='custom treed GP LLM,')
@
<<label=btgpq,fig=TRUE,echo=TRUE,width=7,height=5>>=
main <- 'quantile difference,'
plot(moto.tgp$X[,1], moto.tgp$Zp.q, type='l', main=main)
@
\vspace{-0.5cm}
\caption{\footnotesize {\em top} Posterior predictive distribution
  using a custom parameterized {\tt tgp} call on the motorcycle
  accident data: mean and 90\% credible interval; {\em bottom}
  Quantile-norm (90\%-5\%) showing input-dependent noise.}
\label{f:moto:tgp}
\end{figure}
The resulting posterior predictive surface is shown in {\em top} half
of Figure \ref{f:moto:tgp}.  The {\em bottom} half of the figure shows
the norm (difference) in predictive quantiles, clearly illustrating
the treed GP's ability to capture input-specific noise in the
posterior predictive distribution.

Other permutations of possible models, functions and arguments, for
this data is contained in the {\tt b*} and {\tt tgp} examples sections
of the respective {\tt R} help files.
